/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Model.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class Buscar extends javax.swing.JDialog {

    boolean ejecutaUsuario = false;

    /**
     * Creates new form Baja
     */
    public Buscar(javax.swing.JFrame parent, boolean modal) throws DAO_Excep {
        super(parent, modal);
        DAOSQL d = new DAOSQL();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        nombreslista.removeAllItems();
        info.setText("");
        if (filtro.getSelectedItem().toString().equals("Humano")) {
            for (Planeta p : d.obtainPlanets()) {
                for (Ser s : p.getPopulation()) {
                    if (s instanceof Humano) {
                        nombreslista.addItem(s.getName());
                    }
                }
            }
        }
        if (getSer(new Ser((String) nombreslista.getSelectedItem())) != null) {
//            info.setText(getSer(new Ser((String) nombreslista.getSelectedItem())).toString()
//                    + "\n" + getPlanetaSer(new Ser((String) nombreslista.getSelectedItem())));
        }
        ejecutaUsuario = true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreslista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(426, 402));
        setPreferredSize(new java.awt.Dimension(400, 440));
        setSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(getMaximumSize());
        jPanel1.setMinimumSize(getMinimumSize());
        jPanel1.setPreferredSize(getPreferredSize());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("Ciudadano");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 10, 0);
        jPanel1.add(titulo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(" Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        nombreslista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nombreslistaItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(nombreslista, gridBagConstraints);

        jScrollPane1.setViewportView(info);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 200;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText(" Filtro: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Andoriano", "Ferengi", "Klingon", "Nibiriano", "Vulcaniano" }));
        filtro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jPanel1.add(filtro, gridBagConstraints);

        salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 40, 10);
        jPanel1.add(salir, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:        
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void filtroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroItemStateChanged
        ejecutaUsuario = false;
        // TODO add your handling code here:
        DAOSQL d = new DAOSQL();
        nombreslista.removeAllItems();
        info.setText("");
        if (filtro.getSelectedItem().toString().equals("Humano")) {
            try {
                for (Planeta p : d.obtainPlanets()) {
                    for (Ser s : p.getPopulation()) {
                        if (s instanceof Humano) {
                            nombreslista.addItem(s.getName());
                        }
                    }
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (filtro.getSelectedItem().toString().equals("Andoriano")) {
            try {
                for (Planeta p : d.obtainPlanets()) {
                    for (Ser s : p.getPopulation()) {
                        if (s instanceof Andoriano) {
                            nombreslista.addItem(s.getName());
                        }
                    }
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (filtro.getSelectedItem().toString().equals("Ferengi")) {
            try {
                for (Planeta p : d.obtainPlanets()) {
                    for (Ser s : p.getPopulation()) {
                        if (s instanceof Ferengi) {
                            nombreslista.addItem(s.getName());
                        }
                    }
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (filtro.getSelectedItem().toString().equals("Klingon")) {
            try {
                for (Planeta p : d.obtainPlanets()) {
                    for (Ser s : p.getPopulation()) {
                        if (s instanceof Klingon) {
                            nombreslista.addItem(s.getName());
                        }
                    }
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (filtro.getSelectedItem().toString().equals("Nibiriano")) {
            try {
                for (Planeta p : d.obtainPlanets()) {
                    for (Ser s : p.getPopulation()) {
                        if (s instanceof Nibiriano) {
                            nombreslista.addItem(s.getName());
                        }
                    }
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (filtro.getSelectedItem().toString().equals("Vulcaniano")) {
            nombreslista.removeAllItems();
            try {
                for (Planeta p : d.obtainPlanets()) {
                    for (Ser s : p.getPopulation()) {
                        if (s instanceof Vulcaniano) {
                            nombreslista.addItem(s.getName());
                        }
                    }
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            if (getSer(new Ser((String) nombreslista.getSelectedItem())) != null) {
//                info.setText(getSer(new Ser((String) nombreslista.getSelectedItem())).toString()
//                        + "\n" + getPlanetaSer(new Ser((String) nombreslista.getSelectedItem())));
            }
        } catch (DAO_Excep ex) {
            Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
        }
        ejecutaUsuario = true;
    }//GEN-LAST:event_filtroItemStateChanged

    private void nombreslistaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nombreslistaItemStateChanged
        if (!ejecutaUsuario) {

        } else {
            info.setText("");
//                info.setText(getSer(new Ser((String) nombreslista.getSelectedItem())).toString()
//                        + "\n" + getPlanetaSer(new Ser((String) nombreslista.getSelectedItem())));
        }
    }//GEN-LAST:event_nombreslistaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Baja dialog = new Baja(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JTextPane info;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nombreslista;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
