package View;

import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Model.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class BuscarModificar extends javax.swing.JDialog {

    /**
     * Creates new form Modificar
     */
    public BuscarModificar(javax.swing.JFrame parent, boolean modal) throws DAO_Excep {
        super(parent, modal);
        DAOSQL d = new DAOSQL();
        initComponents();
        for (Ser ser : d.obtainSeres()) {
            nombresserlista.addItem(ser.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        ModificarHumano = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreciudadano = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nombresserlista = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buscarciudadano = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(" Nombre: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(102, 102, 102)));
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        nombreciudadano.setText(nombresserlista.getName());
        nombreciudadano.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 10);
        jPanel2.add(nombreciudadano, gridBagConstraints);

        ModificarHumano.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 10, 40);
        jPanel1.add(nombresserlista, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 40, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        buscarciudadano.setText("Buscar");
        buscarciudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarciudadanoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 40, 40);
        jPanel1.add(buscarciudadano, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void buscarciudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarciudadanoActionPerformed

        String nombre = (String) nombresserlista.getSelectedItem();
        Ser s = null;
        try {
            s = getSer(new Ser(nombre));
        } catch (DAO_Excep ex) {
            Logger.getLogger(BuscarModificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (s instanceof Vulcaniano) {
            ModificarVulcaniano mdfvul = new ModificarVulcaniano(this, true, new Vulcaniano((String) nombresserlista.getSelectedItem()));
            mdfvul.setLocationRelativeTo(null);
            mdfvul.setVisible(true);
        } else if (s instanceof Andoriano) {
            ModificarAndoriano mdfan = new ModificarAndoriano(this, true, new Andoriano((String) nombresserlista.getSelectedItem()));
            mdfan.setLocationRelativeTo(null);
            mdfan.setVisible(true);
        } else if (s instanceof Klingon) {
            ModificarKlingon mdfki = new ModificarKlingon(this, true, new Klingon((String) nombresserlista.getSelectedItem()));
            mdfki.setLocationRelativeTo(null);
            mdfki.setVisible(true);
        } else if (s instanceof Nibiriano) {
            ModificarNibiriano mdfnib = new ModificarNibiriano(this, true, new Nibiriano((String) nombresserlista.getSelectedItem()));
            mdfnib.setLocationRelativeTo(null);
            mdfnib.setVisible(true);
        } else if (s instanceof Ferengi) {
            ModificarFerengi mdffe = new ModificarFerengi(this, true, new Ferengi((String) nombresserlista.getSelectedItem()));
            mdffe.setLocationRelativeTo(null);
            mdffe.setVisible(true);
        } else if (s instanceof Humano) {
            ModificarHumano modificarhumano = null;
            try {
                modificarhumano = new ModificarHumano(this, true, new Humano((String) nombresserlista.getSelectedItem()));
            } catch (DAO_Excep ex) {
                Logger.getLogger(BuscarModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
            modificarhumano.setLocationRelativeTo(null);
            modificarhumano.setVisible(true);
        }
    }//GEN-LAST:event_buscarciudadanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarModificar dialog = null;
                try {
                    dialog = new BuscarModificar(new javax.swing.JFrame(), true);
                } catch (DAO_Excep ex) {
                    Logger.getLogger(BuscarModificar.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ModificarHumano;
    private javax.swing.JButton buscarciudadano;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreciudadano;
    private javax.swing.JComboBox<String> nombresserlista;
    // End of variables declaration//GEN-END:variables
}
